# Based on the cirrus example.
container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

test_task:
  container:
    matrix:
      - image: golang:latest
      - image: golang:1.13
  modules_cache:
    populate_script: make --debug install_deps
    fingerprint_script: cat go.sum && go version
    folder: $GOPATH/pkg/mod
  coverprofile_cache:
    populate_script: mkdir -p coverprofiles
    fingerprint_script: echo ${CIRRUS_BUILD_ID}
    folder: coverprofiles
    reupload_on_changes: true
  build_script: make --debug all
  test_script: make --debug junit-regtest TESTCOVERPROFILE=coverprofiles/${CIRRUS_TASK_ID}.coverprofile
  always:
    junit_result_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
      type: text/xml
    coverprofile_save_artifacts:
      path: "coverprofile/${CIRRUS_TASK_ID}.coverprofile"

fuzzing_task:
  depends_on:
    - test
  env:
    FUZZIT_API_KEY: ENCRYPTED[576877027ac2ddfdc467b47005d53181d998cb29a7ce4c381b112b6771be0e91ef146dc22804c0ba709afc6685debccd]
    matrix:
      - TYPE: fuzzing
      # local-regression needs to talk to a local docker which we don't have in this environment.
      #- TYPE: local-regression
  container:
    image: gcr.io/fuzzit-public/buster-golang12:2dc7875
  modules_cache:
    populate_script: |
      make GO111MODULE=off --debug install_deps
      GO111MODULE=on go mod vendor
    fingerprint_script: cat go.sum && go version && echo VENDOR
    folder: $CIRRUS_WORKING_DIR/vendor
  setup_script: |
    wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/latest/download/fuzzit_Linux_x86_64
    chmod a+x fuzzit
  build_script: make GO111MODULE=off CXX=clang CXXFLAGS=-fsanitize=fuzzer LIB_FUZZING_ENGINE= --debug ./vm-fuzzer
  test_script: ./fuzzit create job --type=${TYPE} --branch=${CIRRUS_BRANCH} --revision=${CIRRUS_CHANGE_IN_REPO} mtail/internal-vm ./vm-fuzzer

coverage_task:
  depends_on:
    - test
  env:
    COVERALLS_TOKEN: ENCRYPTED[5a842e3c8a8d608cb2d8204cc80bed9d6a89390b54b6a32e0064fc368a80e413a8d2d22d001e847b67acba3ba5a8e43c]
  coverprofile_cache:
    fingerprint_script: echo ${CIRRUS_BUILD_ID}
    folder: coverprofiles
  setup_script: |
    go get github.com/sozorogami/gover
    go get github.com/mattn/goveralls
  build_script: |
    gover coverprofiles coverprofile
    goveralls -coverprofile=coverprofile -service=cirrus-ci
  allow_failures: true
