# Based on the cirrus example.
container:
  image: golang:latest

test_task:
  modules_cache:
    populate_script: make --debug install_deps
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  build_script: make --debug all
  test_script: make --debug junit-regtest
  always:
    junit_result_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
      type: text/xml
