---
# common-build names an anchor which contains all the reusable build
# instructions.
common-build: &common-build
  working_directory: /go/src/github.com/google/mtail
  steps:
    - checkout
    - restore_cache:
        keys:
          - go-mod-v1-{{ checksum "go.sum" }}
    - run: make --debug install_deps
    - run: make --debug smoke
    - run: mkdir -p test-results
    - run: mkdir -p workspace
    - run: go get gotest.tools/gotestsum
    - run:
        name: Run tests and coverage with race detector
        command: gotestsum --junitfile test-results/test-output.xml -- -race -coverprofile=workspace/${CIRCLE_JOB}.coverprofile --covermode=atomic -tags=integration -v -timeout=20m  ./...
        no_output_timeout: 20m
    - save_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"
    - persist_to_workspace:
        root: workspace
        paths:
          - "*.coverprofile"
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results

# go* names anchors which define the Go versions to build with, merging the
# common-build alias above.
go1_12: &go1_12
  <<: *common-build
  docker:
    - image: circleci/golang:1.12

# concurrency* names anchors which define the the concurrency level to run
# tests with.
concurrency_4: &concurrency_4
  environment:
    GOMAXPROCS: 4
concurrency_2: &concurrency_2
  environment:
    GOMAXPROCS: 2
concurrency_1: &concurrency_1
  environment:
    GOMAXPROCS: 1

# The main circle-ci configuration.
version: 2
jobs:
  # The main build steps are the crossproduct of concurrency and go versions.
  build-go1.12-4:
    <<: [*go1_12, *concurrency_4]
  build-go1.12-2:
    <<: [*go1_12, *concurrency_2]
  build-go1.12-1:
    <<: [*go1_12, *concurrency_1]
  
  

  # Coverage collects all the coverage reports from each build and merges them,
  # before sending off to Coveralls.
  coverage:
    working_directory: /go/src/github.com/google/mtail
    environment:
      COVERALLS_TOKEN: AQTCw3bl6FDphbQcMMkgVZBIunz5r3H8b
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make --debug install_deps
      - run:
          name: Generate coverage
          command: |
            ls -lR /tmp/workspace
            go get github.com/sozorogami/gover
            gover /tmp/workspace coverprofile
            make --debug coverage.html
            make upload_to_coveralls
      - store_artifacts:
          path: coverprofile
          destination: coverage
      - store_artifacts:
          path: coverage.html
          destination: coverage

  container:
    working_directory: /go/src/github.com/google/mtail
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          make container

  delivery:
    working_directory: /go/src/github.com/google/mtail
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make --debug install_deps
      - run: make --debug crossbuild
      - run: sha1sum build/*
      - store_artifacts:
          path: build/
      - run:
          name: Upload binaries to GitHub Release
          # GITHUB_TOKEN is a secret from the CircleCI environment
          command: |
            go get github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace ${CIRCLE_TAG?} build/

  fuzzing:
    working_directory: /go/src/github.com/google/mtail
    docker:
      - image: fuzzitdev/golang:1.12.7-buster
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: |
          wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.17/fuzzit_Linux_x86_64
          chmod a+x fuzzit
      - run: |
          make install_deps
          cd internal/vm
          go-fuzz-build -libfuzzer -o fuzzer.a .
          clang-9 -fsanitize=fuzzer fuzzer.a -o fuzzer
      - run: |
          ./fuzzit auth $FUZZIT_API_KEY
          ./fuzzit create job --type fuzzing --branch ${CIRCLE_BRANCH} --revision ${CIRCLE_SHA1} mtail/internal-vm internal/vm/fuzzer

  fuzz-regression:
    working_directory: /go/src/github.com/google/mtail
    docker:
      - image: fuzzitdev/golang:1.12.7-buster
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: |
          wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.17/fuzzit_Linux_x86_64
          chmod a+x fuzzit
      - run: |
          make install_deps
          cd internal/vm
          go-fuzz-build -libfuzzer -o fuzzer.a .
          clang-9 -fsanitize=fuzzer fuzzer.a -o fuzzer
      - run: |
          ./fuzzit create job --type regression --local --branch ${CIRCLE_BRANCH} --revision ${CIRCLE_SHA1} mtail/internal-vm internal/vm/fuzzer

# tag-filter ensures that jobs run for version-tagged changes as well as
# regular commits.  Use for all normal build and test and stats (coverage)
# jobs.
tag-filter: &tag-filter
  filters:
    tags:
      only: /^v.*/

# tag-and-branch-filter ensures that jobs run only for *only* version-tagged
# changes; excluding all branches to avoid triggering on all commits. Use for
# all release jobs.
tag-and-branch-filter: &tag-and-branch-filter
  filters:
    tags:
      only: /^v.*/
    # Explicitly disable all branches, otherwise we match on every
    # commit.
    branches:
      ignore: /.*/

# Using workflows to sequence each of our builds in parallel, and coverage
# depending on all of them.  These two lists need to be updated when the inputs
# of the build matrix change.
workflows:
  version: 2
  build_and_deliver:
    jobs:
      - build-go1.12-4:
          <<: *tag-filter
      - build-go1.12-2:
          <<: *tag-filter
          requires:
            - build-go1.12-4
      - build-go1.12-1:
          <<: *tag-filter
          requires:
            - build-go1.12-4
      - coverage:
          <<: *tag-filter
          requires:
            - build-go1.12-4
            - build-go1.12-2
            - build-go1.12-1
      - fuzz-regression:
          <<: *tag-filter
          requires:
            - build-go1.12-4
      - fuzzing:
          <<: *tag-filter
          filters:
            branches:
              # pull requests don't have access to the Fuzzit API key.
              ignore: /pull\/.*/
          requires:
            - build-go1.12-4
      - container:
          <<: *tag-and-branch-filter
          requires:
            - coverage
      - delivery:
          <<: *tag-and-branch-filter
          requires:
            - container
